version: "3.8"

services:
  wstunnel-client:
    image: ghcr.io/erebe/wstunnel:latest
    container_name: wstunnel-client
    command:
      - "/home/app/wstunnel"
      - "client"
      - "--local-to-remote"
      - "udp://0.0.0.0:${LOCAL_WG_PORT:-51820}:wg-easy:51820?timeout_sec=${WSS_UDP_TIMEOUT:-30}"
      - "--log-lvl"
      - "${WST_LOG_LEVEL:-INFO}"
      - "wss://${WSS_DOMAIN}:${WSS_PORT:-443}"
    ports:
      - "${LOCAL_WG_PORT:-51820}:${LOCAL_WG_PORT:-51820}/udp"
    restart: unless-stopped
